/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
	uint32_t *p_ClkCtrlReg=(uint32_t*)0x40023830;
	uint32_t *pPortDModeReg=(uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg=(uint32_t*)0x40020C14;
	*p_ClkCtrlReg |=0x08;
	*pPortDModeReg &=0xFCFFFFFF;
	*pPortDModeReg |=0X01000000;
	*pPortDOutReg |=0X1000;






    /* Loop forever */
	for(;;);
}
